
--
    name: 'Login Actions'
    uriPattern: 'login/{@action}'
    defaults:
      @package: Events
      @controller: Login
      @action: 'index'

--
    name: 'Default action'
    uriPattern: 'location/{@action}'
    defaults:
      @package: Events
      @controller: Location
      @format: 'json'
--
    name: 'Default action'
    uriPattern: '{@action}'
    defaults:
      @package: Events
      @controller: Event
      @format: 'json'

--
    name: 'Homepage'
    uriPattern: ''
    defaults:
      @package: Events
      @controller: Event
      @format: 'html'
      @action: 'index'


